// AUTH
export const SET_TOKENS = 'SET_TOKENS'
export const SET_AUTH_LOADING = 'SET_AUTH_LOADING'
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const SET_AUTH_REGISTER_RESULT = 'SET_AUTH_REGISTER_RESULT'
export const CLEAR_AUTH_MESSAGES = 'CLEAR_AUTH_MESSAGES'
export const LOGOUT_AUTH = 'LOGOUT_AUTH'


// BOOK
export const SET_BOOKS = 'SET_BOOKS'
export const ADD_BOOKS = 'ADD_BOOKS'
export const SET_BOOK_LOADING = 'SET_BOOK_LOADING'
export const SET_BOOK_CATEGORIES = 'SET_BOOK_CATEGORIES'
export const SET_FIRST_BOOK_LIKES = 'SET_FIRST_BOOK_LIKES'


// USER
export const SET_USER_LIKE = 'SET_USER_LIKE'
export const ADD_USER_LIKE = 'ADD_USER_LIKE'
export const REMOVE_USER_LIKE = 'REMOVE_USER_LIKE'
export const SET_USER_LOADING = 'SET_USER_LOADING'
export const SET_USER_BOOKS = 'SET_USER_BOOKS'
export const ADD_USER_BOOKS = 'ADD_USER_BOOKS'

// INIT
export const SET_INIT_STATUS = 'SET_INIT_STATUS'

// AUTHOR
export const SET_AUTHOR_INFO_BOOKS = 'SET_AUTHOR_INFO_BOOKS'
export const SET_AUTHOR_LOADING = 'SET_AUTHOR_LOADING'